### ISSUE TITLE
Some pictures not showing because of localised numbers with decimal comma in srcset

### ISSUE THREAD

**Issue by MacLake** [django-cms/djangocms-picture#108]
At least {{ picture_size.size.0 }}px in line 32 of the template picture.html
can have a decimal comma in some cases which causes the image not to be
displayed in Firefox 95.0b8 and Chrome 96.0.4664.45.

Fixed in https://github.com/MacLake/djangocms-picture/commit/c76cabaafc9d759fb332fec6a0841c90e3179274

**Comment by fabien-michel** [comment]
I also have this exact same issue with django cms 3.9.0, djangocms-picture 3.0.0 and french localized django.

Exemple of `img` tag generated:

```html
<img src="/my_picture__1751.0x632.0_q85_subsampling-2.jpg" alt="" srcset="
    /my_picture__576x576_q85_subsampling-2.jpg 576w,
    /my_picture__768x768_q85_subsampling-2.jpg 768w,
    /my_picture__992x992_q85_subsampling-2.jpg 992w,
    /my_picture__1751.0x632.0_q85_subsampling-2.jpg 1751,0w
" sizes="
    (max-width: 576px) 576px,
    (max-width: 768px) 768px,
    (max-width: 992px) 992px,
    1751,0px
">
```

Notice the `1751,0w` that should be `1751w` and `1751,0px`  that should be `1751px`

I think adding [|floatformat filter](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#floatformat) to the both `picture_size.size.0` would be an easy fix

**Comment by MacLake** [comment]
I have already created a PR with `{% localize off %}`. I think that’s the cleanest way to avoid localization of numbers. But also `|floatformat:"0"` would do the trick.

The maintainer requested me to do a unit test which was way more complicated than fixing this issue, because he fears a potential regression. I don’t see any danger at all. I will talk a bout it in the technical committee of the django CMS association today. Personally I have just solved it by using my own fork, or just the template, but we should fix this.

**Comment by MacLake** [comment]
Well, in this case you’re right: We don’t need a float number in this case, and therefore we shouldn’t have one. But in general float numbers are possible in JavaScript, and they don’t work if they are localised with a decimal comma like in German and French. And `{% localize off %}` turns off localisation, which I think is the cleanest way of making sure not to use localised numbers.

So I think it’s a good idea to have this in JS in general (though I must admit, I only use it in my JS code when I get into trouble).

**Comment by fabien-michel** [comment]
Ok, 
`AbstractPicture.picture` is of type of type `FilerImageField` which is a ForeignKey to `filer.model.Image` based on [filer.model.BaseImage](https://github.com/django-cms/django-filer/blob/master/filer/models/abstract.py).

the `BaseImage._width` and `BaseImage._height` are FloatField since the following filer PR: https://github.com/django-cms/django-filer/pull/1226
14 months ago they use to be IntergerField.

I think the fix is to round the output values of `AbstractPicture.get_size`.
I'll try to do a PR for this

**Comment by MacLake** [comment]
Anyway, we talked today about this issue and my PR was accepted. So at least we have a fix in the master branch now.

**Comment by fabien-michel** [comment]
Ok nice. I've created PR to fix the get_size issue.

**Comment by fabien-michel** [comment]
The bug seems to be still here with even with a dot in the number. At lest on Firefox 98.
The larger image (the one with the float number) is never loaded by the browser which select the image with sized a bit little.
When I force the number to be integer(see my patch) the larger image is loaded as expected.

**Comment by MacLake** [comment]
Well, for me the bug has vanished with my fix. Can you see all logos on [this page (de](https://outphit.eu/de/unsere-aufgabe/unser-team/) / [fr)](https://outphit.eu/fr/outphit/notre-equipe/)? My colleagues have uploaded logos that are way too big, so that django-picture applies the thumbnail set with this floating number, incl. the first logo. Tkae a look at the HTML source. It was this page where I noticed this bug.

**Comment by fabien-michel** [comment]
I thinks it work on the page because the larger image is not loaded by the browser. For exemple, the picture climate_alliance_logo_en.png is displayed using the 992px version. The bug will occur with the 4724px version.

**Comment by fabien-michel** [comment]
I fact, actually the bug already occur on this page. The selected version is 992px whereas the expected to be selected by browser is the 4724px version according to the max-width rule.

```html
<img class="ui image" src="climate_alliance_logo_en.png__4724.0x3350.0_subsampling-2.png" alt="" srcset="
    climate_alliance_logo_en.png__576x576_subsampling-2.png 576w,
    climate_alliance_logo_en.png__768x768_subsampling-2.png 768w,
    climate_alliance_logo_en.png__992x992_subsampling-2.png 992w,
    climate_alliance_logo_en.png__4724.0x3350.0_subsampling-2.png 4724.0w
" sizes="
    (max-width: 576px) 576px,
    (max-width: 768px) 768px,
    (max-width: 992px) 992px,
    4724.0px
">
```

On a laptop the viewport width is around 1920px. So the 992px should not be selected. But because of the number with dot the 4724px version isn't selected and Firefox fallback to the wider valid version.

You can try to edit HTML in dev tools to remove the both ".0" and you will see in network tab that firefox load the 4724px version

**Comment by mogoh** [comment]
I had this issue myself today and @fabien-michel s pull-request fixed it for me.
Please reopen this issue until it gets fixed.
Please merge the pull request.
(The pull requests new conflict has to be resolved, though.)

**Comment by fsbraun** [comment]
Merged today.
